--[[--------------------------------------------------------------------------
    GideonRaid / UI / Intermission.lua

    RENDERING LAYER ONLY ("Intermission Coach"). This file may call the WoW API
    (frames, fonts, C_Timer, GetBindingKey). It contains NO business computation:
    everything comes from ns.Intermission (snapshot / setupView / run machine),
    from ns.Simulation (rehearsal view, ping help view) and from ns.Layout (the
    DISPOSITION of the panel: frame size, every offset, every label).

    THE DISPOSITION IS PURE (Core/Layout.lua). History: the fourth in-game test
    showed the big state ("2V2R") drawn ON TOP of the SIMULATION banner, because
    every element was placed with a FIXED Y offset. Here, no element carries a
    literal offset any more: UI.IntermissionRefresh() builds a spec (the current
    texts), Core measures and STACKS the blocks, and UI.ApplyLayout applies the
    result as-is. Two blocks can therefore never share a Y, in English as in
    French (tests/spec/layout_spec.lua locks it down for both languages).

    12.x prohibitions (see docs/CONVENTIONS.md):
      - no read of aura / health / resource (possible SECRET value);
      - no combat log event;
      - no addon -> addon message in an instance.

    PING: THE PLAYER PINGS, WITH THE NATIVE BLIZZARD PING KEYBIND. Measured in
    game by the raid lead: an addon CANNOT ping at all - neither from a macro nor
    from a binding ("action usable only by the Blizzard UI"). This file therefore
    READS the key the player bound (GetBindingKey, under pcall) only to DISPLAY
    it, and never pings, never prepares a macro.

    FLOW OF A RAID EVENING (only the ENCOUNTER_START arguments are read, and ALWAYS
    under pcall - see the boss filter block further down):
      a. before the pull, /gr -> "PLACE INTERMISSION PANEL": the frame is shown
         in placement mode and displays ONLY the Gideon illustration the raid
         lead delivered (no button, no text). It is dragged where the player
         wants it, the position is saved in the SavedVariables and `/gr inter ok`
         validates it;
      b. the player prepares the ping keybind and confirms with `/gr inter ok`
         -> panel closed;
      c. ENCOUNTER_START decides: IF the encounter is the configured target boss
         (allow-list of encounter ids, `/gr boss <id>`) OR the manual override is
         armed (/gr inter on), the pre-computed schedule is armed and the panel
         opens BY ITSELF shortly before each intermission. On any other boss
         NOTHING opens (safe default) and the chat says how to configure the right
         boss;
      d. the player clicks the composition they see (REDO corrects a mistake);
      e. at the end of the intermission the panel closes BY ITSELF;
      f. the next intermission follows the same cycle, automatically.
    THIS REAL FLOW IS UNCHANGED by the simulation mode below.

    WHICH BOSS: the allow-list of ENCOUNTER_START ids is the PRIMARY criterion (an
    integer, identical in every game language) and it is EMPTY by default, so the
    panel NEVER opens on its own until the raid lead names the right boss. The id
    of Entombed Sentinels is NOT known yet: `/gr idlog on` prints and memorizes
    what ENCOUNTER_START reports ("encounter seen: id=<id> name=<n> difficulty=<d>
    group=<g>"), and that line is what `/gr boss <id>` is given. The names are a
    SECONDARY criterion, language dependent, therefore empty by default too.

    THE PANEL IS THE RAID LEAD'S SURFACE, NOT A DOCUMENT (in-game report: "enleve
    tout le blabla"). It is read during a fight, so it carries NO sentence at all:
      - BEFORE a click: the THREE CARDS, stacked VERTICALLY, each one drawing the
        raid lead's own screenshot of the orbs (Texture/*.tga, a 256 px box,
        generated by tools/make_textures.py) inside a thin border. Nothing else -
        no title, no state line, no role line, no action line, no key reminder.
        The order is FROZEN by Core/Layout.INTERMISSION_CHOICE_ORDER (3V1R, 2V2R,
        1V3R from top to bottom) and a test locks it down;
      - AFTER a click: ONE WORD and nothing else - "Ping" (1V3R) and "Chasseur"
        (3V1R) in the theme GREEN, "BOSS" (2V2R) in the BIGGEST font of the
        window (44 px / 64 px, an EXPLICIT file and size from Core/Layout) - plus
        CORRECT, which brings the three pictures back. The colors come from
        Core/Layout.THEME (one constant, never a color written here);
      - IN PLACEMENT MODE: the illustration the raid lead delivered, and NOTHING
        else (no button, no label).
    The close cross ("X") is the ONLY way to close the panel: the former Close
    BUTTON was a sentence too many, and the cross was already there.
    WHERE A LEFTOVER TITLE COULD HIDE (raid-lead report: "there is still a title
    at the top of the intermission panel"): UI.ApplyLayout EMPTIES every element
    it is handed before showing the ones Core computed, this file creates NO
    title FontString any more (p.title is NOT set), Core/Layout.violations()
    REFUSES any text block a panel is not allowed to write
    (Layout.panelTextIds), and the strings that used to carry a title
    (ui.panelTitle, the placement blob of Intermission.setupView) are DELETED -
    a test asserts they can not come back.

    NO SOUND IS EVER PLAYED BY ITSELF (raid-lead decision): the three
    assignment soundboards (`Sound/assign-*.ogg`) play ONCE, on the Master
    channel, when the player CLICKS one of the three composition buttons - in the
    real flow as in a rehearsal - and NOTHING plays at any other moment: not when
    the panel opens (by itself or through `/gr sim inter`), not when it closes,
    not on a tick, not in a simulation that was not clicked. `Sound/
    intermission-start.ogg` STAYS packaged (the raid lead may want it back) and
    `/gr sound test start` plays it on REQUEST, but no automatic playback path
    exists any more - tests/spec/sound_spec.lua fails if one comes back.
    Core/Sound.lua owns the pure table state -> file and the one-playback-per-
    assignment gate; THIS file is the only one that calls PlaySoundFile, under
    pcall, so a missing file or a refused call leaves the addon silent without a
    Lua error and without blocking the rest of the rendering. CORRECT re-arms the
    gate (the next click plays the sound of the new composition) and so does
    every new intermission.

    THE PANEL ALWAYS DISAPPEARS WHEN THE INTERMISSION IS OVER. Two mechanisms,
    in this order:
      1. the intermission clock reaches DONE (Core/Intermission.tick) and this
         layer hides the panel - the normal path;
      2. the BOUNDED AUTO-CLOSE guard (Core/Intermission.newCloseGuard) is armed
         when the panel opens and RE-ARMED at every new intermission; its delay
         is configurable (Config.autoCloseSeconds, 30 s by default: the measured
         25 s window of a real intermission plus a 5 s margin) and can never be
         shorter than the real window, so it can only catch the cases where the
         normal close never happened (a clock that stopped ticking, a panel shown
         with no intermission running). A frame left on screen over the raid was
         reported in game: it is a bug, and this guard is the fix.

    CLOSE CROSS ("X", top right) on BOTH panels (the main one, UI/Panel.lua, and
    this one), and on the intermission panel it is THE way to close: during the
    placement it CANCELS the placement (same effect as the former Close button);
    during a REHEARSAL it CLOSES the rehearsal (the player is the one who closes
    it); during the real flow it only HIDES the panel: the intermission clock
    keeps running, the panel still closes by itself at the end and opens again at
    the next intermission (nothing is disarmed).

    SIMULATION MODE (two entries, reachable from the main panel AND from the
    chat): see the dedicated block below. It never arms, disarms or advances the
    ENCOUNTER_START timeline, never touches the live intermission state, never
    publishes a decision into the SavedVariables and never reads a combat event.
    Fourth in-game test: the rehearsal OPENS IMMEDIATELY and is closed by the
    player (no delay, no automatic close, one single cycle), and the ping entry
    is a plain HELP WINDOW (no guided sequence).
----------------------------------------------------------------------------]]
--
--
--
local _, ns = ...

--- Core/Locale.lua is loaded BEFORE this file by the .toc (every string
--- displayed in game goes through it: English by default, French on frFR).
local Locale = assert(ns.Locale, "Core/Locale.lua must be loaded before UI/Intermission.lua")

--- Core/Simulation.lua is loaded BEFORE this file by the .toc: the pure logic of
--- the two simulations (sequences, bounds, refusals) lives there, this layer only
--- renders it and feeds it the injected time step.
local Simulation = assert(ns.Simulation, "Core/Simulation.lua must be loaded before UI/Intermission.lua")

--- Core/Sound.lua is loaded BEFORE this file by the .toc: it owns the PURE table
--- "canonical state -> soundboard file", the one-playback-per-assignment gate and
--- the bounded preference. THIS layer is the only one that plays anything.
local Sound = assert(ns.Sound, "Core/Sound.lua must be loaded before UI/Intermission.lua")

--- Core/Intermission.lua is loaded BEFORE this file by the .toc: it owns the
--- state machine, the snapshot displayed and the bounded auto-close guard. THIS
--- layer only renders and feeds it the injected time step.
local Intermission = assert(ns.Intermission, "Core/Intermission.lua must be loaded before UI/Intermission.lua")

--- Core/BossFilter.lua is loaded BEFORE this file by the .toc: it owns the PURE
--- decision "is this encounter the target boss?" (allow-list of encounter ids +
--- optional names, SAFE DEFAULT = nothing opens) and the observation of the
--- ENCOUNTER_START arguments. THIS layer only renders the decision and reads the
--- event; the decision itself is never taken here.
local BossFilter = assert(ns.BossFilter, "Core/BossFilter.lua must be loaded before UI/Intermission.lua")

--- Core/Layout.lua is loaded BEFORE this file by the .toc: it owns the WHOLE
--- disposition of the panel (the frozen vertical order of the three image
--- buttons, the size of each picture, the texture path of each state and THE
--- THEME - the only color values of the addon). THIS layer applies it as-is:
--- it writes neither a color nor a texture path and computes no geometry.
local Layout = assert(ns.Layout, "Core/Layout.lua must be loaded before UI/Intermission.lua")

local UI = ns.UI or {}
ns.UI = UI

--- Constant local time step (never read from the client): Core/ stays pure and
--- deterministic, testable with an injected dt.
local TICK_SECONDS = 0.1

local panel, ticker, state, run, setupMode

--- ONE-PLAYBACK-PER-ASSIGNMENT gate of the assignment soundboards (Core/Sound.lua).
--- It is reset at every new intermission, at every rehearsal and by CORRECT: a
--- repeated declaration of the SAME composition is sounded once, and a new
--- declaration plays the sound of the NEW composition (documented behaviour).
local soundAssigner = Sound.newAssigner()

--- BOUNDED AUTO-CLOSE guard (Core/Intermission.newCloseGuard): armed when the
--- panel opens, RE-ARMED at every new intermission, ticked with the same constant
--- dt as the state machine. It is the safety net that guarantees the panel can
--- NEVER stay on screen once the intermission is over (see the header).
local closeGuard = Intermission.newCloseGuard()

--- SIMULATION MODE owns its OWN run and state (see the block further down): the
--- rehearsal can therefore never arm, disarm or move the real flow. The ping
--- entry owns no state at all any more: it is a plain INFORMATION window.
local simRun, simState, pingPanel

--- API ref 12.x: https://warcraft.wiki.gg/wiki/Secret_Values
--- Constraint: this panel only displays strings written by the player (a click
--- on a composition) or prepared out of game (GIDEON SavedVariables). No unit
--- value is read, hence no comparison on a secret value.
local function config()
    local db = _G.GideonRaidDB
    return ns.Config.resolveIntermission(db and db.intermission)
end

--- Reads the key the PLAYER bound to one of the native ping keybinds
--- (Options > Keybindings > ping system) - API:
--- https://warcraft.wiki.gg/wiki/API_GetBindingKey
--- READ ONLY, under pcall, and it is the ONLY ping-related API this addon
--- touches: it never sends a ping (the ping API is restricted to Blizzard's UI).
--- The candidates come from Core (their exact names are still to be confirmed in
--- game); a wrong candidate or a missing API simply means "no key known", and the
--- panel then asks for a keybind instead of showing a shortcut that does not
--- exist.
--- @param bindNames table|nil candidate binding names, ordered
--- @return string|nil key ("Q", "ALT-F", ...)
local function resolveBindingKey(bindNames)
    if type(bindNames) ~= "table" then
        return nil
    end
    if type(_G.GetBindingKey) ~= "function" then
        return nil
    end
    for index = 1, #bindNames do
        local ok, key = pcall(_G.GetBindingKey, bindNames[index])
        if ok and type(key) == "string" and key ~= "" then
            return key
        end
    end
    return nil
end

--- ---------------------------------------------------------------------------
--- ASSIGNMENT SOUNDBOARDS: the ONLY audio call of the whole addon.
--- ---------------------------------------------------------------------------

--- Plays one sound file on the MASTER channel. The FILE and the CHANNEL are
--- decided by Core/Sound.lua; this layer only hands them to the client.
--- API ref 12.x: https://warcraft.wiki.gg/wiki/API_PlaySoundFile
--- Constraint: a file that does not exist, a path the client refuses or an API
--- that is not there must leave the addon SILENT, without an error and without
--- interrupting the rest of the rendering: hence the type() guard and the pcall,
--- exactly like the ping keybind read above (GetBindingKey).
--- @param path string|nil client path ("Interface\AddOns\GideonRaid\Sound\...")
--- @param channel string|nil sound channel ("Master")
--- @return boolean played
local function playSoundFile(path, channel)
    if type(path) ~= "string" or path == "" then
        return false
    end
    if type(_G.PlaySoundFile) ~= "function" then
        return false
    end
    local ok = pcall(_G.PlaySoundFile, path, channel)
    return ok == true
end

--- THE ASSIGNMENT SOUNDBOARD of the composition the player just declared (real
--- flow as in a rehearsal). Core decides: one file per canonical state, ONE
--- playback per assignment, and the player preference; an unknown declaration, a
--- disabled preference or an already sounded assignment simply stays silent.
--- @param declaration string|nil canonical state ("1V3R" | "2V2R" | "3V1R")
--- @return boolean played
function UI.PlayAssignSound(declaration)
    local c = config()
    local request = Sound.takeAssignSound(soundAssigner, declaration, c.soundEnabled)
    if request == nil then
        return false
    end
    return playSoundFile(request.path, request.channel)
end

--[[ NO AUTOMATIC SOUND, EVER (raid-lead decision, replacing the former behaviour)

     The INTERMISSION START SOUND (`Sound/intermission-start.ogg`) used to be
     fired here, once, the moment the panel opened. It is NOT any more: NOTHING
     plays by itself, and the ONLY trigger of any sound is a CLICK on one of the
     three composition buttons (see UI.IntermissionDeclare -> UI.PlayAssignSound).

     What is left:
       - the file stays PACKAGED (Sound/ + GideonRaid.toc) and Core/Sound.lua
         keeps the pure gate (Sound.newStartGate / Sound.takeIntermissionStart):
         the raid lead can get the automatic playback back with a handful of
         lines, and the gate is still covered by tests/spec/sound_spec.lua;
       - `/gr sound test start` (UI.SoundTestStart below) still plays it ON
         REQUEST, so the file can be checked in game without waiting for a pull.

     THIS layer therefore calls no start sound at any point: opening the panel
     (automatic or `/gr sim inter`), closing it, a tick or a re-render are all
     SILENT. tests/spec/sound_spec.lua guards that silence: it fails as soon as
     an automatic playback path comes back.
]]

--- Remembers the current assignment (CORRECT, `/gr inter stop`, every new
--- intermission and every rehearsal): the NEXT click plays the sound of the
--- composition it declares - the natural behaviour after a correction.
function UI.ResetAssignSound()
    Sound.resetAssigner(soundAssigner)
    return soundAssigner
end

--- `/gr sound test start`: plays the INTERMISSION START sound on request, so the
--- raid lead can check it WITHOUT waiting for a pull. The player preference is
--- honoured, exactly like the three assignment soundboards: a muted sound stays
--- silent and says so, so a test can never contradict the setting.
--- @return boolean played
function UI.SoundTestStart()
    local c = config()
    if not c.soundEnabled then
        UI.Print(Locale.t("cmd.sound.testDisabled"))
        return false
    end
    local played = playSoundFile(Sound.startPath(), Sound.CHANNEL)
    if not played then
        UI.Print(Locale.format("cmd.sound.failed", tostring(Sound.START_FILE)))
        return false
    end
    UI.Print(Locale.format("cmd.sound.testStart", tostring(Sound.START_FILE)))
    return true
end

--- `/gr sound test <1v3r|2v2r|3v1r|start>`: plays ONE sound on request, so the
--- raid lead can hear and identify the files WITHOUT waiting for a fight.
--- BOUNDED: an unknown value is REFUSED (nothing is played), and the player
--- preference is honoured - a muted sound stays silent and says so, so a test can
--- never contradict the setting.
--- @param raw string|nil state written by the player ("1v3r", "2V2R", "start")
--- @return boolean played
function UI.SoundTest(raw)
    local flat = type(raw) == "string" and raw:lower():gsub("%s+", "") or ""
    if flat == "start" or flat == "intermission-start" then
        return UI.SoundTestStart()
    end
    local resolved = Sound.resolveState(raw)
    if resolved == nil then
        UI.Print(Locale.format("cmd.sound.unknownState", tostring(raw)))
        return false
    end
    local c = config()
    if not c.soundEnabled then
        UI.Print(Locale.t("cmd.sound.testDisabled"))
        return false
    end
    local played = playSoundFile(Sound.pathFor(resolved), Sound.CHANNEL)
    if not played then
        UI.Print(Locale.format("cmd.sound.failed", tostring(Sound.fileName(resolved))))
        return false
    end
    UI.Print(Locale.format("cmd.sound.test", resolved, tostring(Sound.fileName(resolved))))
    return true
end

--- The engine ticks only while something is timed: a SIMULATION (rehearsal or
--- ping test), the encounter clock (waiting for the next intermission), the
--- intermission itself, or the BOUNDED AUTO-CLOSE guard (armed from the moment
--- the panel opens: without it the guard would never fire on a panel opened with
--- no intermission running, which is exactly the frame left on screen).
local function engineActive()
    if simRun ~= nil then
        return true
    end
    if run ~= nil then
        return true
    end
    if Intermission.closeGuardArmed(closeGuard) then
        return true
    end
    local phase = state ~= nil and state.phase or nil
    return phase == ns.Intermission.PHASE.PENDING or phase == ns.Intermission.PHASE.VISIBLE or phase == ns.Intermission.PHASE.DARK
end

--- The state the panel is CURRENTLY showing. During a rehearsal the panel shows
--- the SIMULATION state: the live intermission (`state`) is never read nor
--- modified by a simulation.
local function displayedState()
    if simRun ~= nil then
        return simState
    end
    return state
end

local function stopTicker()
    if ticker then
        ticker:Cancel()
        ticker = nil
    end
end

local function ensureTicker()
    if ticker then
        return ticker
    end
    ticker = C_Timer.NewTicker(TICK_SECONDS, function()
        UI.IntermissionTick(TICK_SECONDS)
    end)
    return ticker
end

--- Reads one color of THE THEME (Core/Layout.THEME) as the three RGB floats the
--- client expects. The rendering layer writes NO color of its own: a green
--- scattered in this file is exactly how a green drifts away from the theme
--- between two releases. An unknown name falls back to the theme green, never to
--- a nil the client would refuse.
--- DECLARED HERE, before every frame builder: a Lua local is only visible to the
--- functions defined AFTER it.
--- @param name string theme key ("GREEN" | "BOSS" | "SIMULATION")
--- @return number r, number g, number b
local function themeColor(name)
    local entry = Layout.THEME[name] or Layout.THEME.GREEN
    return entry.r, entry.g, entry.b
end

local function ensurePanel()
    if panel then
        return panel
    end

    local p = CreateFrame("Frame", "GideonRaidIntermissionPanel", UIParent, "BackdropTemplate")
    p:SetSize(560, 360)
    p:SetMovable(true)
    p:EnableMouse(true)
    p:RegisterForDrag("LeftButton")
    p:SetClampedToScreen(true)
    p:SetScript("OnDragStart", function(self)
        self:StartMoving()
    end)
    p:SetScript("OnDragStop", function(self)
        self:StopMovingOrSizing()
        UI.IntermissionSavePosition()
    end)
    p:SetBackdrop({
        bgFile = "Interface\\DialogFrame\\UI-DialogBox-Background",
        edgeFile = "Interface\\DialogFrame\\UI-DialogBox-Border",
        tile = true,
        tileSize = 32,
        edgeSize = 32,
        insets = { left = 8, right = 8, top = 8, bottom = 8 },
    })

    -- NO fixed offset anywhere: the size, the position and the label of every
    -- element below come from Core/Layout.intermissionPanel(), applied as-is by
    -- UI.ApplyLayout. See the header: the "big state on top of the banner" bug
    -- came from literal Y offsets.
    --
    -- THERE IS NO TITLE, NO STATE LINE, NO ROLE LINE, NO ACTION LINE AND NO KEY
    -- REMINDER ANY MORE: the raid lead had them removed ("enleve tout le
    -- blabla"), and the layout no longer contains such a block, so there is no
    -- frame left for them either.

    -- CLOSE CROSS ("X", top right). Label and tooltip come from Core/Locale.lua
    -- (ui.closeCross / ui.closeTooltip), shared with the main panel. It is THE
    -- way to close the panel (the former Close BUTTON is gone).
    p.closeCross = UI.AttachCloseCross(p, function()
        UI.IntermissionCloseCross()
    end)

    -- The SIMULATION banner: displayed ONLY while a rehearsal drives the panel.
    -- The ONE text left, and only there: during the real flow the panel shows
    -- pictures and nothing else.
    p.simBanner = p:CreateFontString(nil, "OVERLAY", "GameFontNormalLarge")
    p.simBanner:SetJustifyH("CENTER")
    p.simBanner:SetText("")
    p.simBanner:SetTextColor(themeColor("SIMULATION"))
    p.simBanner:Hide()

    -- THE ONE WORD written after a click ("Ping" / "BOSS" / "Chasseur"). TWO
    -- FontStrings, because a FontString carries ONE font: "wordBig" is the middle
    -- composition - the biggest element of the WINDOW, as the raid lead asked -
    -- and "word" carries the two others. Core/Layout.wordBlockId() decides which
    -- one the layout contains; the color comes from Core/Layout.THEME.
    -- THE FONT IS EXPLICIT: the addon creates its own FontString and calls
    -- SetFont(file, size, "") with the file and the sizes of Core/Layout (44 px
    -- and 64 px). A Blizzard font OBJECT would hide its real size - an addon
    -- cannot read it out of game - so "the biggest element of the window" would
    -- be a promise nobody could verify.
    p.word = p:CreateFontString(nil, "OVERLAY")
    p.word:SetFont(Layout.WORD_FONT_FILE, Layout.WORD_SIZE, "")
    p.word:SetJustifyH("CENTER")
    p.word:SetText("")
    p.word:Hide()

    p.wordBig = p:CreateFontString(nil, "OVERLAY")
    p.wordBig:SetFont(Layout.WORD_FONT_FILE, Layout.WORD_SIZE_BIG, "")
    p.wordBig:SetJustifyH("CENTER")
    p.wordBig:SetText("")
    p.wordBig:Hide()

    p.buttons = {}
    -- THE THREE CARDS: the player clicks the PICTURE of the composition they see
    -- above their head. The order (top to bottom) is FROZEN by Core
    -- (Layout.INTERMISSION_CHOICE_ORDER: 3V1R, 2V2R, 1V3R) and the picture itself
    -- is the texture of the state (Core/Textures.pathFor, applied by the layout):
    -- this layer writes no label at all.
    -- A CARD, not a Blizzard button: a thin border and a discreet dark background
    -- around the picture (Core/Layout.BUTTON_STYLES through UI.CreateCard), no
    -- chrome, no text, and ONE single feedback - the border lights up under the
    -- mouse (UI.CardBorder). Which style is used is Core's choice, never ours.
    -- ONCE THE CHOICE IS CLICKED the three pictures DISAPPEAR (Core decides:
    -- snapshot.showButtons): the layout no longer contains them, so they are
    -- HIDDEN and can never be drawn on top of the SIMULATION banner. CORRECT
    -- brings the three choices back.
    for index = 1, #ns.Layout.INTERMISSION_CHOICE_ORDER do
        local key = ns.Layout.INTERMISSION_CHOICE_ORDER[index]
        local button = UI.CreateCard("Button", p, ns.Layout.CHOICE_STYLE)
        button.state = key
        button:RegisterForClicks("LeftButtonUp")
        button:SetScript("OnEnter", function(self)
            UI.CardBorder(self, UI.CARD_STATE.HOVER)
        end)
        button:SetScript("OnLeave", function(self)
            UI.CardBorder(self, UI.CARD_STATE.REST)
        end)
        button:SetScript("OnMouseDown", function(self)
            UI.CardBorder(self, UI.CARD_STATE.PRESSED)
        end)
        button:SetScript("OnMouseUp", function(self)
            UI.CardBorder(self, UI.CARD_STATE.HOVER)
        end)
        button:SetScript("OnClick", function()
            UI.IntermissionDeclare(key)
        end)
        p.buttons[index] = button
    end

    -- THE PLACEMENT ILLUSTRATION (the drawing of the WINDOW itself). A plain card
    -- (no Button: there is nothing to click on the picture) holding the picture
    -- the raid lead delivered. Core/Layout.placementPanel() sizes it and names its
    -- style; the panel is DRAGGABLE, the cross cancels and /gr inter ok validates.
    p.placement = UI.CreateCard("Frame", p, ns.Layout.CHOICE_STYLE)

    -- REDO / CORRECT: forgets the declaration and brings the three pictures back.
    -- Usable as many times as needed (the state machine stays untouched). It is
    -- the ONLY written button of the panel - and only AFTER a click: before the
    -- click the panel writes nothing at all.
    p.redo = CreateFrame("Button", nil, p, "UIPanelButtonTemplate")
    p.redo:SetScript("OnClick", function()
        UI.IntermissionRedo()
    end)
    p.redo:Hide()

    -- THE OK BUTTON OF THE PLACEMENT PANEL (raid-lead decision: "Remet oui ok").
    -- A small, discreet button UNDER the illustration: it saves the position and
    -- closes, exactly like `/gr inter ok` - which stays available as a backup. It
    -- is part of the PLACEMENT layout only (Core/Layout.placementPanel): during a
    -- fight the layout does not contain it, so the applier hides it, and it can
    -- never be drawn over the three composition cards.
    p.placementOk = CreateFrame("Button", nil, p, "UIPanelButtonTemplate")
    p.placementOk:SetScript("OnClick", function()
        UI.IntermissionConfirmSetup()
    end)
    p.placementOk:Hide()

    p:Hide()
    panel = p
    return panel
end

--- The elements of the intermission panel, by block id (Core/Layout.lua names
--- every block). The rendering layer only maps an id to its frame.
--- @return table array of { id = string, frame = Frame|FontString }
local function panelElements(p)
    return {
        { id = "simBanner", frame = p.simBanner },
        { id = "choice1", frame = p.buttons[1] },
        { id = "choice2", frame = p.buttons[2] },
        { id = "choice3", frame = p.buttons[3] },
        { id = "word", frame = p.word },
        { id = "wordBig", frame = p.wordBig },
        { id = "redo", frame = p.redo },
        { id = "placement", frame = p.placement },
        { id = "placementOk", frame = p.placementOk },
    }
end

--- Applies the EXPLICIT font Core declared for the word block of the layout: the
--- file and the size travel WITH the block, so the rendering layer writes neither
--- a file name nor a size (one single source, in Core/Layout.lua). Both
--- FontStrings can be refreshed by a single layout (only one of them is in it).
--- @param p Frame the intermission panel
--- @param layout table the layout just applied
local function applyWordFonts(p, layout)
    local targets = { word = p.word, wordBig = p.wordBig }
    for index = 1, #layout.blocks do
        local block = layout.blocks[index]
        local target = targets[block.id]
        if target ~= nil and type(block.fontFile) == "string" and type(block.fontSize) == "number" then
            if type(target.SetFont) == "function" then
                target:SetFont(block.fontFile, block.fontSize, "")
            end
        end
    end
end

--- Applies the configured scale + position (no business computation).
function UI.IntermissionApplyConfig()
    local p = ensurePanel()
    local c = config()
    local pos = c.position
    p:SetScale(c.scale)
    p:ClearAllPoints()
    p:SetPoint(pos.point, UIParent, pos.relativePoint, pos.x, pos.y)
end

--- Saves the current panel position into the SavedVariables.
function UI.IntermissionSavePosition()
    local p = ensurePanel()
    local db = _G.GideonRaidDB
    if type(db) ~= "table" or type(db.intermission) ~= "table" then
        return
    end
    db.intermission.position = UI.CapturePosition(p)
end

--- Applies the PERSISTED position of the ping-training frame (centered by
--- default). Called before the frame is shown, so the player always finds it
--- where they left it. Does nothing while the frame does not exist yet (it is
--- built lazily, on the first simulation).
function UI.PingPanelApplyPosition()
    if pingPanel == nil then
        return nil
    end
    local db = _G.GideonRaidDB
    local pos = ns.Config.resolvePosition(type(db) == "table" and db.pingPanelPosition or nil)
    pingPanel:ClearAllPoints()
    pingPanel:SetPoint(pos.point, UIParent, pos.relativePoint, pos.x, pos.y)
    return pos
end

--- Saves the position of the ping-training frame (drag stop).
function UI.SavePingPanelPosition()
    if pingPanel == nil or type(_G.GideonRaidDB) ~= "table" then
        return nil
    end
    _G.GideonRaidDB.pingPanelPosition = UI.CapturePosition(pingPanel)
    return _G.GideonRaidDB.pingPanelPosition
end

--- Rebuilds the display from what Core/ computed AND applies the PURE layout.
--- The panel shows PICTURES and, once a composition is declared, ONE WORD: the
--- long explanations live in docs/, never on screen (raid-lead request: "enleve
--- tout le blabla").
--- ONCE A COMPOSITION IS CLICKED Core hides the three image buttons
--- (snapshot.showButtons = false) and shows CORRECT: the layout then simply does
--- not contain them, so the applier HIDES them (they can never be drawn on top
--- of the banner) and only the word stays.
--- UI APPLIES, CORE DECIDES: every block of the layout - its order, its size,
--- its texture, its label, the font of the word - is computed by
--- ns.Layout.intermissionPanel, and the COLOR of the word by ns.Layout.wordColor.
--- @return table the snapshot currently displayed
function UI.IntermissionRefresh()
    local p = ensurePanel()
    local c = config()
    local spec = {}

    if setupMode then
        -- PLACEMENT MODE (before the pull): the illustration the raid lead
        -- delivered (Core/Layout.placementPanel) and its small OK button UNDER it,
        -- and NOTHING ELSE. No composition, no label: the picture IS the reference
        -- of the size and the spot the window will occupy during the fight. The OK
        -- button saves the position and closes (UI.IntermissionConfirmSetup), the
        -- cross cancels, `/gr inter ok` does the same as the button, and the panel
        -- is dragged to the wanted spot like the combat panel.
        return UI.ApplyLayout(p, Layout.placementPanel(c.style), panelElements(p))
    end

    -- The ping policy is INJECTED into Core (Core never reads the SavedVariables)
    -- and decides the role order and the "PING: YES/NO" decision (still used by
    -- the chat commands, no longer displayed on the panel).
    -- During a rehearsal the panel shows the SIMULATION view: the live
    -- intermission (`state`) is left untouched (see displayedState()).
    local snap = Intermission.snapshot(displayedState(), c.pingMode, resolveBindingKey)
    if simRun ~= nil then
        -- Rehearsal: the SIMULATION banner (the ONE text the panel may show).
        snap = Simulation.forRehearsal(snap, simRun)
        spec.bannerLines = snap.simBannerLines
    end
    spec.showChoices = snap.showButtons
    spec.showRedo = snap.showRedo
    -- THE STYLE OF THE CARDS: the raid lead's choice (`/gr style`), the delivered
    -- one by default. It travels WITH the layout, so the combat panel's look is
    -- decided in ONE place (Core/Layout.BUTTON_STYLES) and this layer only applies
    -- the table it is handed.
    spec.style = c.style
    -- THE WORD: absent until a composition is declared, and always paired with
    -- the STATE it belongs to (never parsed back from the text).
    spec.wordText = snap.word
    spec.wordState = snap.wordKey

    local layout = Layout.intermissionPanel(spec)
    UI.ApplyLayout(p, layout, panelElements(p))
    -- THE FONT OF THE WORD comes from the layout block (Core decided the file and
    -- the size): the addon's own FontString, never an inherited Blizzard font
    -- object. Applied on every refresh, so a language or a state change can never
    -- leave a stale size behind.
    applyWordFonts(p, layout)
    -- THE COLOR OF THE WORD comes from THE THEME (Core): the two survival words
    -- are green, the big BOSS is gold. Both FontStrings take it (only one of them
    -- is part of the layout), so a language or a state change can never leave a
    -- stale color behind.
    if snap.wordKey ~= nil then
        local color = Layout.wordColor(snap.wordKey)
        p.word:SetTextColor(color.r, color.g, color.b)
        p.wordBig:SetTextColor(color.r, color.g, color.b)
    end
    return snap
end

--- Shows the COMBAT panel (automatic opening, manual toggle, rehearsal). The
--- BOUNDED AUTO-CLOSE guard is armed here, so the panel can never stay on screen
--- once the intermission is over, whatever path opened it (see the header):
---   - a rehearsal owns its own life: the PLAYER closes it (raid-lead decision),
---     so the guard is NOT armed for it;
---   - the placement mode is a configuration step, not a fight: no guard either.
function UI.IntermissionShow()
    local p = ensurePanel()
    setupMode = false
    UI.IntermissionApplyConfig()
    p:Show()
    UI.IntermissionRefresh()
    if simRun == nil then
        UI.ArmAutoClose()
    end
end

--- ARMS (or RE-ARMS) the bounded auto-close guard of the panel with the delay
--- Core/ computed: the configured safety delay, stretched to the whole real
--- window of the current intermission when that is longer (it can therefore never
--- cut a real intermission short). Called when the panel opens and at every new
--- intermission.
--- @return number delay seconds
function UI.ArmAutoClose()
    local c = config()
    local timeline = type(state) == "table" and state.timeline or nil
    local delay = Intermission.closeDelay(timeline, c.autoCloseSeconds)
    Intermission.armCloseGuard(closeGuard, delay)
    ensureTicker()
    return delay
end

--- Hides the panel. Nothing is left running: the auto-close guard is DISARMED
--- (the panel is gone; the next opening re-arms it) and a rehearsal is forgotten
--- (a rehearsal that is no longer on screen must not stay "running", otherwise
--- the next /gr sim inter would be refused).
function UI.IntermissionHide()
    local p = ensurePanel()
    setupMode = false
    p:Hide()
    Intermission.disarmCloseGuard(closeGuard)
    if simRun ~= nil then
        -- Hiding the panel ENDS a rehearsal: a rehearsal that is no longer on
        -- screen must not stay "running" (the next /gr sim inter would be refused
        -- and the player would be stuck with a hidden simulation).
        simRun = nil
        simState = nil
    end
end

--[[ SIMULATION MODE (rehearsal alone, with no boss and no raid) ----------------

     Two entries, reachable from the MAIN panel (two buttons) and from the chat
     (/gr sim inter | group | groupe, /gr sim ping, /gr sim stop):

       1. "INTERMISSION GROUP": the intermission panel opens RIGHT AWAY (fourth
          in-game test: the former 3 s delay is gone), the player clicks their
          composition, corrects it (CORRECT) and CLOSES THE PANEL THEMSELVES
          (close cross or Close button). ONE single cycle: nothing closes it
          automatically and nothing relaunches it. No boss, no raid, no
          ENCOUNTER_START, no combat event ever read;
       2. "PING HELP": a SHORT information window: how to bind one key per ping
          (Options > Keybindings > Ping) and what to do during the boss ("when
          the panel says PING: YES, hover YOUR OWN character frame and press
          your key: you ping yourself"). The former GUIDED SEQUENCE (countdown,
          three announced pings, "ping placed" button) is REMOVED: measured in
          game, the addon can neither send nor detect a ping, so there was
          nothing to sequence.

     ISOLATION: the rehearsal owns its own run (`simRun`) and state (`simState`),
     never touches `run` (the pre-computed ENCOUNTER_START timeline) nor `state`
     (the live intermission), never arms/disarms the timeline and never publishes
     a decision into the SavedVariables (a rehearsal must never be read by the
     diagnostic kit as a real choice).
]]
--

--- True while the REAL flow is running (live intermission, or the
--- ENCOUNTER_START timeline armed): a rehearsal is then REFUSED, so a simulation
--- can never be mistaken for a real fight.
local function realFlowBusy()
    if run ~= nil then
        return true
    end
    if type(state) ~= "table" then
        return false
    end
    local phase = state.phase
    return phase == ns.Intermission.PHASE.PENDING or phase == ns.Intermission.PHASE.VISIBLE or phase == ns.Intermission.PHASE.DARK
end

--- THE SAME PREDICATE, EXPORTED: the STYLE SHOWCASE (UI/Showcase.lua) refuses to
--- open while a real fight is running or a timeline is armed, exactly like a
--- rehearsal does. Nothing else may call it, and the showcase is the only surface
--- outside this file that needs to know.
--- @return boolean
function UI.IntermissionRealFlowBusy()
    return realFlowBusy()
end

--- True while the INTERMISSION REHEARSAL is running. The ping help window is NOT
--- a simulation: it owns no state, times nothing and never blocks anything.
local function simulationRunning()
    return simRun ~= nil
end

--- Forgets every simulation (SILENT) and hides what they own. Idempotent.
local function clearSimulation()
    simRun = nil
    simState = nil
    -- The rehearsal is over: its assignment soundboard is forgotten too.
    UI.ResetAssignSound()
    if pingPanel ~= nil then
        pingPanel:Hide()
    end
    if panel ~= nil and panel:IsShown() then
        panel:Hide()
    end
    if not engineActive() then
        stopTicker()
    end
end

--- The PING HELP window (an information frame, not an intermission: the two can
--- never overlap on screen conceptually, and the intermission panel always
--- wins). Like the main panel it is DRAGGABLE and its position is persisted
--- (GideonRaidDB.pingPanelPosition).
local function ensurePingPanel()
    if pingPanel then
        return pingPanel
    end
    local p = CreateFrame("Frame", "GideonRaidPingHelpPanel", UIParent, "BackdropTemplate")
    p:SetMovable(true)
    p:EnableMouse(true)
    p:RegisterForDrag("LeftButton")
    p:SetClampedToScreen(true)
    p:SetScript("OnDragStart", function(self)
        if UI.IsPanelLocked() then
            UI.Print(Locale.t("panel.lockedHint"))
            return
        end
        self:StartMoving()
    end)
    p:SetScript("OnDragStop", function(self)
        self:StopMovingOrSizing()
        UI.SavePingPanelPosition()
    end)
    p:SetBackdrop({
        bgFile = "Interface\\DialogFrame\\UI-DialogBox-Background",
        edgeFile = "Interface\\DialogFrame\\UI-DialogBox-Border",
        tile = true,
        tileSize = 32,
        edgeSize = 32,
        insets = { left = 8, right = 8, top = 8, bottom = 8 },
    })

    -- No fixed offset: Core/Layout.pingHelpPanel() lays the window out.
    p.title = p:CreateFontString(nil, "OVERLAY", "GameFontNormal")
    p.title:SetJustifyH("CENTER")
    p.title:SetText("")

    p.closeCross = UI.AttachCloseCross(p, function()
        UI.PingHelpHide()
    end)

    -- The BIG reminder, in large type: what to do, not a countdown.
    p.headline = p:CreateFontString(nil, "OVERLAY", "GameFontNormalLarge")
    p.headline:SetJustifyH("CENTER")
    p.headline:SetText("")

    p.body = p:CreateFontString(nil, "OVERLAY", "GameFontHighlight")
    p.body:SetJustifyH("LEFT")
    p.body:SetJustifyV("TOP")
    p.body:SetText("")

    -- The keys the player really bound, when they are known (read by the
    -- rendering layer under pcall and injected into Core).
    p.keys = p:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
    p.keys:SetJustifyH("LEFT")
    p.keys:SetJustifyV("TOP")
    p.keys:SetText("")

    -- Leaving the window: nothing is simulated and nothing is timed, so this
    -- button only closes an information frame.
    p.close = CreateFrame("Button", nil, p, "UIPanelButtonTemplate")
    p.close:SetScript("OnClick", function()
        UI.PingHelpHide()
    end)

    p:Hide()
    pingPanel = p
    return pingPanel
end

--- The elements of the ping help window, by block id (Core/Layout names them).
--- @return table array of { id = string, frame = Frame|FontString }
local function pingHelpElements(p)
    return {
        { id = "title", frame = p.title },
        { id = "headline", frame = p.headline },
        { id = "body", frame = p.body },
        { id = "keys", frame = p.keys },
        { id = "close", frame = p.close },
    }
end

--- Rebuilds the ping help window from the PURE view computed by Core (the key of
--- each ping is INJECTED: Core never calls an API).
--- @return table the applied layout
function UI.PingHelpRefresh()
    local p = ensurePingPanel()
    local view = Simulation.pingHelpView(resolveBindingKey)
    local layout = ns.Layout.pingHelpPanel({ lines = view.lines, keyLines = view.keyLines })
    return UI.ApplyLayout(p, layout, pingHelpElements(p))
end

--- Shows the ping help window (`/gr sim ping`, the main-panel button), where the
--- player left it (persisted position).
function UI.PingHelpShow()
    local p = ensurePingPanel()
    UI.PingPanelApplyPosition()
    p:Show()
    UI.PingHelpRefresh()
end

--- Hides the ping help window. Nothing to disarm: this frame simulates nothing.
function UI.PingHelpHide()
    if pingPanel ~= nil then
        pingPanel:Hide()
    end
end

--- `/gr sim` with no argument and the main-panel SIMULATION buttons land here.
--- The whole argument is parsed by Core (mode + no option any more); an unknown
--- sub-command or a trailing option is REFUSED with a message, nothing is
--- guessed and nothing is launched.
function UI.SimulationCommand(raw)
    local mode, options, err = Simulation.parseCommand(raw)
    if mode == nil then
        if err ~= nil then
            UI.Print(tostring(err))
        end
        UI.Print(Locale.format("cmd.sim.unknown", tostring(raw)))
        UI.Print(Locale.t("cmd.sim.help"))
        return
    end
    if mode == "inter" then
        UI.SimulationInterStart(options)
    elseif mode == "ping" then
        UI.SimulationPingStart()
    elseif mode == "style" then
        -- `/gr sim style [1..6|gideon]`: the STYLE SHOWCASE - every font size, the
        -- palette with its hex codes, the three states of a card, the seven frame
        -- styles and the two animations, shown IN GAME so the raid lead chooses
        -- there. An unknown candidate is refused by the showcase itself.
        UI.ShowcaseOpen(options.argument)
    elseif mode == "anim" then
        -- `/gr sim anim on|off`: the showcase animations (fade-in + border pulse),
        -- persisted. Unknown value refused, like `/gr sound on|off`.
        UI.ShowcaseAnimationsCommand(options.argument)
    else
        UI.SimulationStop()
    end
end

--- Starts the "INTERMISSION GROUP" rehearsal (`/gr sim inter`, aliases group and
--- groupe, plus the main-panel button): the panel opens IMMEDIATELY and the
--- PLAYER closes it (fourth in-game test). ONE cycle, no automatic close, no
--- relaunch, no boss, and the ENCOUNTER_START timeline is left alone.
--- @param options table|nil any option is REFUSED by Core
function UI.SimulationInterStart(options)
    local c = config()
    if not c.enabled then
        UI.Print(Locale.t("ui.disabled"))
        return
    end
    if realFlowBusy() then
        UI.Print(Locale.t("sim.refused.live"))
        return
    end
    if simulationRunning() then
        UI.Print(Locale.t("sim.refused.running"))
        return
    end
    local newRun, err = Simulation.newRun(options)
    if newRun == nil then
        UI.Print(Locale.format("ui.intermissionError", tostring(err)))
        return
    end
    clearSimulation()
    simRun = newRun
    simState = ns.Intermission.newState()
    -- NO lead time: the simulated intermission starts VISIBLE at once, and it is
    -- never ticked: without a boss there is no clock, the player closes it.
    local started, startErr = ns.Intermission.start(simState, {
        leadSeconds = 0,
        visibilitySeconds = c.visibilitySeconds,
        durationSeconds = c.durationSeconds,
    })
    if not started then
        simRun = nil
        simState = nil
        UI.Print(Locale.format("ui.intermissionError", tostring(startErr)))
        return
    end
    -- NEW REHEARSAL: the soundboard gate is re-armed (see beginIntermission), so
    -- the first click of the rehearsal plays the sound of the composition it
    -- declares. NOTHING else is played here: a rehearsal opens SILENTLY (the raid
    -- lead removed the automatic intermission-start playback).
    UI.ResetAssignSound()
    -- The rehearsal owns its own life: the PLAYER closes it, so the bounded
    -- auto-close guard is NOT armed for it (it would close the rehearsal under
    -- the player's hands). UI.IntermissionShow skips it for a simulation.
    UI.IntermissionShow()
    UI.Print(Locale.t("cmd.sim.inter"))
end

--- Starts... rather, SHOWS the PING HELP window (`/gr sim ping`, main-panel
--- button): how to bind the keys and the operational reminder. The addon never
--- pings and detects nothing.
function UI.SimulationPingStart()
    local c = config()
    if not c.enabled then
        UI.Print(Locale.t("ui.disabled"))
        return
    end
    if realFlowBusy() then
        UI.Print(Locale.t("sim.refused.live"))
        return
    end
    UI.PingHelpShow()
    UI.Print(Locale.format("cmd.sim.pingStart", Simulation.pingSequenceLine()))
end

--- Stops the REHEARSAL (`/gr sim stop`, the close cross, the Close button) and
--- hides the ping help window. Idempotent: with nothing running it says so.
function UI.SimulationStop()
    local stopped = false
    if simRun ~= nil then
        Simulation.closeRun(simRun)
        stopped = true
    end
    if pingPanel ~= nil and pingPanel:IsShown() then
        stopped = true
    end
    clearSimulation()
    if stopped then
        UI.Print(Locale.t("cmd.sim.closed"))
    else
        UI.Print(Locale.t("cmd.sim.none"))
    end
end

--- Close cross of the INTERMISSION panel:
---   - in PLACEMENT mode it CANCELS the placement (same effect as the existing
---     Close button: the mode is left, the panel is hidden);
---   - during a REHEARSAL it CLOSES the rehearsal (the player owns it);
---   - during the REAL flow it only hides the panel: the intermission clock keeps
---     running, the panel still closes by itself at the end of the intermission
---     and opens again at the next one (nothing is disarmed).
function UI.IntermissionCloseCross()
    if setupMode then
        UI.IntermissionHide()
        return
    end
    UI.IntermissionClosePanel()
end

--- Close button AND close cross of the intermission panel: ONE behaviour for
--- both. A rehearsal is CLOSED BY THE PLAYER (nothing else ends it); the real
--- flow is only hidden (its clock keeps running).
function UI.IntermissionClosePanel()
    if simRun ~= nil then
        UI.SimulationStop()
        return
    end
    UI.IntermissionHide()
end

--- Enters PLACEMENT MODE: the intermission panel is shown before the pull so the
--- player can drag it where they want it (position saved) and read how to
--- prepare the ping keybind. Pressing OK closes it (step b of the flow).
function UI.IntermissionSetup()
    local c = config()
    if not c.enabled then
        UI.Print(Locale.t("ui.disabled"))
        return
    end
    if simulationRunning() then
        -- A rehearsal is showing: the placement would fight it for the panel.
        UI.Print(Locale.t("sim.refused.running"))
        return
    end
    local p = ensurePanel()
    UI.IntermissionApplyConfig()
    setupMode = true
    p:Show()
    UI.IntermissionRefresh()
end

--- OK button of the placement panel: saves the position and closes.
function UI.IntermissionConfirmSetup()
    if not setupMode then
        return
    end
    UI.IntermissionSavePosition()
    UI.IntermissionHide()
    UI.Print(Locale.t("ui.setupDone"))
end

--- Manual key/button: shows (or hides) the intermission panel.
function UI.IntermissionToggle()
    local p = ensurePanel()
    if p:IsShown() then
        UI.IntermissionHide()
        return
    end
    local c = config()
    if not c.enabled then
        UI.Print(Locale.t("ui.disabled"))
        return
    end
    UI.IntermissionShow()
end

--- Starts ONE intermission (SILENT: no sound is played by itself any more): state
--- machine in PENDING, then VISIBLE... Used by the schedule (step c) and by the
--- manual commands.
--- @param c table resolved configuration
--- @return boolean started
local function beginIntermission(c)
    if state == nil then
        state = ns.Intermission.newState()
    end
    local started, err = ns.Intermission.start(state, {
        leadSeconds = c.leadSeconds,
        visibilitySeconds = c.visibilitySeconds,
        durationSeconds = c.durationSeconds,
    })
    if not started then
        UI.Print(Locale.format("ui.intermissionError", tostring(err)))
        return false
    end
    -- NEW INTERMISSION: the assignment soundboard gate is re-armed, so the SAME
    -- composition declared at the next intermission plays its sound again.
    UI.ResetAssignSound()
    -- THE PANEL OPENS: `leadSeconds` before the intermission. NO SOUND here (the
    -- raid lead removed the automatic intermission-start playback): the panel
    -- opening arms the bounded auto-close guard, nothing else.
    ensureTicker()
    UI.IntermissionShow()
    return true
end

--- Manual start (`/gr inter start`): verbose, the player asked for it.
function UI.IntermissionStart()
    local c = config()
    if not c.enabled then
        UI.Print(Locale.t("ui.disabled"))
        return
    end
    if simulationRunning() then
        -- A rehearsal is running: stop it first (/gr sim stop) so a simulated
        -- intermission is never mistaken for a real one.
        UI.Print(Locale.t("sim.refused.running"))
        return
    end
    if beginIntermission(c) then
        UI.Print(Locale.format("ui.started", c.visibilitySeconds))
    end
end

function UI.IntermissionStop()
    stopTicker()
    if state ~= nil then
        ns.Intermission.reset(state)
    end
    UI.ResetAssignSound()
    UI.IntermissionHide()
end

function UI.IntermissionReset()
    stopTicker()
    if state ~= nil then
        ns.Intermission.reset(state)
    end
    UI.IntermissionRefresh()
end

--- Advances by one tick. dt is injected by the engine (local constant): Core
--- never reads the client clock.
---   0. the SIMULATIONS (intermission rehearsal, guided ping test): they own their
---      own run/state and never touch the two clocks below;
---   1. the encounter clock (ENCOUNTER_START is the origin, its arguments are
---      never read) opens the panel shortly before each pre-computed intermission;
---   2. the intermission clock counts the lead time, the visibility window, the
---      darkened room, then DONE -> the panel CLOSES BY ITSELF;
---   3. the BOUNDED AUTO-CLOSE guard: if the panel is STILL on screen once its
---      deadline has passed (a clock that never reached DONE, a panel opened with
---      no intermission running), it is hidden here. The panel can therefore never
---      stay over the raid after the intermission is over.
function UI.IntermissionTick(dt)
    -- The SIMULATION owns NO clock of its own any more: the panel opens right
    -- away and the player closes it (fourth in-game test), so nothing is ticked
    -- here. The clocks below are the REAL flow's, untouched by a rehearsal.
    if run ~= nil then
        local _, openedIndex = ns.Intermission.advanceRun(run, dt)
        if openedIndex ~= nil then
            -- A new intermission starts NOW: the panel opens (and, with it, the
            -- bounded auto-close guard is re-armed).
            beginIntermission(config())
        end
        if ns.Intermission.runFinished(run) then
            run = nil
        end
    end
    if state ~= nil then
        local phase = state.phase
        if phase == ns.Intermission.PHASE.PENDING or phase == ns.Intermission.PHASE.VISIBLE or phase == ns.Intermission.PHASE.DARK then
            ns.Intermission.tick(state, dt)
            if state.phase == ns.Intermission.PHASE.DONE then
                UI.IntermissionHide()
            end
        end
    end
    -- 3. THE SAFETY NET. Ticked even when no intermission is running (the guard
    -- is armed from the moment the panel opens), and it hides the panel exactly
    -- once: a frame left on screen over the raid was reported in game.
    if Intermission.tickCloseGuard(closeGuard, dt) then
        UI.IntermissionHide()
    end
    -- Rendering: only the intermission panel is redrawn (the ping help window is
    -- static: it shows the same text until it is closed).
    if panel ~= nil and panel:IsShown() then
        UI.IntermissionRefresh()
    end
    if not engineActive() then
        stopTicker()
    end
end

--- Player declaration: click on a COMPOSITION button (3V1R / 2V2R / 1V3R).
--- A bare ambiguous number ("1" or "3" alone) is refused by Core with a message
--- asking for the dominant color.
--- The ASSIGNMENT SOUNDBOARD of the declared state is played HERE, once, the
--- moment the declaration is accepted (real flow and rehearsal alike): nothing is
--- played without a declaration, and Core/Sound.lua refuses a second playback of
--- the same assignment (CORRECT re-arms it).
function UI.IntermissionDeclare(declaration)
    local c = config()
    if not c.enabled then
        UI.Print(Locale.t("ui.disabled"))
        return
    end
    -- SIMULATION: the click belongs to the REHEARSAL state, and NOTHING is
    -- published into the SavedVariables: the diagnostic kit must never read a
    -- rehearsal as a real decision.
    if simRun ~= nil then
        if simState == nil then
            UI.Print(Locale.t("sim.notOpen"))
            return
        end
        local _, simErr = ns.Intermission.declare(simState, declaration)
        if simErr ~= nil then
            UI.Print(Locale.format("ui.declarationRefused", tostring(simErr)))
            return
        end
        UI.PlayAssignSound(simState.declaration)
        UI.IntermissionRefresh()
        return
    end
    if state == nil or state.phase == ns.Intermission.PHASE.IDLE or state.phase == ns.Intermission.PHASE.DONE then
        -- Manual use outside a scheduled intermission (key, button, command).
        if not beginIntermission(c) then
            return
        end
    end
    local _, err = ns.Intermission.declare(state, declaration)
    if err ~= nil then
        UI.Print(Locale.format("ui.declarationRefused", tostring(err)))
        return
    end
    -- The soundboard of the state just declared, played ONCE (see Core/Sound.lua).
    UI.PlayAssignSound(state.declaration)
    -- We PUBLISH the timestamped decision into the SavedVariables: the
    -- diagnostic kit (GideonDiagAddon) reads it afterwards, with no chat input
    -- during combat and no inter-addon communication.
    local db = _G.GideonRaidDB
    if type(db) == "table" then
        local clock
        if type(date) == "function" then
            clock = date("%Y-%m-%d %H:%M:%S")
        end
        ns.Config.recordDecision(db, {
            composition = state.declaration,
            at = (type(time) == "function") and time() or nil,
            clock = clock,
            source = "coach-panel",
        })
    end
    UI.IntermissionRefresh()
end

--- REDO / CORRECT button: forgets the declaration and shows the three
--- composition choices again. Usable as many times as the player wants.
--- It also RE-ARMS the assignment soundboard: the next click plays the sound of
--- the composition it declares, even when it is the same one (documented).
function UI.IntermissionRedo()
    -- The state CURRENTLY shown: during a rehearsal it is the simulation state, so
    -- REDO corrects the simulated declaration and never the live one.
    local target = displayedState()
    if target == nil then
        return
    end
    local _, err = ns.Intermission.clearDeclaration(target)
    if err ~= nil then
        UI.Print(Locale.format("ui.redoFailed", tostring(err)))
        return
    end
    UI.ResetAssignSound()
    UI.IntermissionRefresh()
end

--[[ WHICH BOSS MAY OPEN THE PANEL (critical bug, fixed here) ------------------

     REPORTED BY THE RAID LEAD: "the window opens by itself during ANY boss fight!
     It must be limited to the boss we want."

     The panel used to be armed on EVERY `ENCOUNTER_START`. The decision is now a
     PURE FUNCTION of Core/BossFilter.lua:

       - the target is an ALLOW-LIST OF ENCOUNTER IDS (`ENCOUNTER_START` arg1: an
         INTEGER, the same on every client whatever the game language) plus an
         optional allow-list of NAMES (arg2, which the CLIENT translates: it stays
         EMPTY by default and is never guessed);
       - an EMPTY allow-list means NO AUTOMATIC OPENING (SAFE DEFAULT). A panel
         that does not open is better than a panel that opens on the wrong boss -
         and the chat says how to configure the right boss;
       - `/gr inter on` stays the MANUAL OVERRIDE: it arms the panel for the NEXT
         encounter whatever the boss, and it is CONSUMED at the end of it;
       - the arguments are read UNDER pcall (in 12.x an argument may be a SECRET
         value, and comparing one raises): an id that cannot be read is simply NOT
         a match, hence no opening - never a Lua error, never the wrong boss;
       - `/gr idlog on` is the MEASUREMENT mechanism: the real id of the target
         boss is read in game ("encounter seen: id=<id> ..."), never invented.

     Everything else of the flow is unchanged: the schedule arms on the pull, the
     panel opens `leadSeconds` before each intermission, closes at the end and
     opens again at the next one.
]]

--- The PURE decision of Core/BossFilter.lua, called UNDER pcall: the comparison
--- itself must be protected (a SECRET value raises on the smallest operation), and
--- ANY failure is a REFUSAL - never an automatic opening on an unknown boss.
--- @param encounter table|nil observation built by BossFilter.observeEncounter
--- @return table decision { shouldOpen, reason, id, name }
function UI.BossDecision(encounter)
    local ok, decision = pcall(BossFilter.evaluate, encounter, config())
    if not ok or type(decision) ~= "table" then
        return { shouldOpen = false, reason = BossFilter.REASON.UNREADABLE }
    end
    return decision
end

--- The chat line that says WHY nothing opens and WHAT to do about it: neither the
--- cleared target (a deliberate choice) nor a missing one must look like a bug. Pure
--- formatting, no state.
--- @param decision table|nil
--- @param resolved table|nil resolved configuration (to tell "cleared on purpose" from
---   "no target at all")
--- @return string message
function UI.BossRefusalMessage(decision, resolved)
    local reason = type(decision) == "table" and decision.reason or nil
    if reason == BossFilter.REASON.NO_TARGET then
        local c = type(resolved) == "table" and resolved or {}
        if c.bossTargetCleared == true then
            -- `/gr boss clear` was used: the short message names the command that
            -- brings the target back instead of repeating the whole procedure.
            return Locale.t("cmd.boss.clearedHint")
        end
        return Locale.t("cmd.boss.noTarget")
    end
    if reason == BossFilter.REASON.UNREADABLE then
        return Locale.t("cmd.boss.unreadable")
    end
    if type(decision) == "table" and decision.id ~= nil then
        return Locale.format("cmd.boss.notTarget", BossFilter.idText(decision.id))
    end
    return Locale.t("cmd.boss.notTargetNoId")
end

--- IDLOG (`/gr idlog on`): the measurement mechanism. Every `ENCOUNTER_START` is
--- printed - each value read under pcall, an unreadable value says so instead of
--- showing a fake number - and memorized NEWEST FIRST in the SavedVariables
--- (`GideonRaidDB.intermission.seenEncounters`, bounded), so the raid lead can
--- read the real id back after the pull. Nothing is sent anywhere, nothing is
--- invented: the id logged here IS the measured truth (the delivered default target
--- comes from exactly such a line), and any other boss is measured the same way.
--- @param encounter table|nil observation built by BossFilter.observeEncounter
--- @return boolean recorded
function UI.RecordSeenEncounter(encounter)
    UI.Print(BossFilter.seenLine(encounter))
    local db = _G.GideonRaidDB
    if type(db) ~= "table" then
        return false
    end
    local entry = BossFilter.toEntry(encounter)
    if type(time) == "function" then
        entry.at = time()
    end
    if type(date) == "function" then
        entry.clock = date("%Y-%m-%d %H:%M:%S")
    end
    ns.Config.recordSeen(db, entry)
    return true
end

--- Load-time warning (`PLAYER_LOGIN`): when NOTHING can open by itself, the player
--- MUST know it, otherwise the feature looks like a broken addon. Two different
--- situations, and only the FIRST one is worth a warning:
---   - no target at all (a build without any delivered default): warn;
---   - the target was cleared ON PURPOSE (`/gr boss clear`, `bossTargetCleared`): the
---     player knows what they did, and a warning at every login would read as if the
---     addon had forgotten something - stay silent.
--- Recomputed on every login: as soon as a target exists again, nothing is printed.
--- @return boolean printed
function UI.PrintBossFilterWarning()
    local c = config()
    if BossFilter.hasTarget(c) then
        return false
    end
    if c.bossTargetCleared == true then
        return false
    end
    UI.Print(Locale.t("cmd.boss.noTarget"))
    return true
end

--- ENCOUNTER_START is an instance event, not a combat log one. IT IS THE ONLY
--- place the auto-opening is decided: the schedule is armed ONLY when this
--- encounter is the configured target (or when the manual override is armed).
--- @param encounter table|nil observation built by Core/BossFilter.observeEncounter
function UI.IntermissionOnEncounterStart(encounter)
    -- A rehearsal must NEVER compete with a real fight: it is stopped the moment
    -- the encounter starts. This arms/disarms nothing by itself: the timeline
    -- below is armed exactly as before.
    if simRun ~= nil or (pingPanel ~= nil and pingPanel:IsShown()) then
        clearSimulation()
        UI.Print(Locale.t("sim.stoppedByEncounter"))
    end
    local c = config()

    -- IDLOG: measured BEFORE any decision, and even when the coach is disabled -
    -- the player asked for it explicitly and it is a measurement tool, not a
    -- decision. The id logged here is what `/gr boss <id>` will be given.
    if c.idlog then
        UI.RecordSeenEncounter(encounter)
    end

    if not c.enabled or not c.startOnEncounterStart then
        return
    end

    local decision = UI.BossDecision(encounter)
    if not decision.shouldOpen then
        -- NOTHING is armed for THIS encounter (the target boss is the ONLY one that
        -- may open the panel by itself, and the delivered default of the addon makes
        -- it work out of the box), and a schedule left over by a previous fight is
        -- disarmed too, so the panel can never open itself on the wrong boss. The
        -- refusal says WHICH case it is: cleared on purpose, no target at all, or
        -- simply another boss.
        run = nil
        if not engineActive() then
            stopTicker()
        end
        UI.Print(UI.BossRefusalMessage(decision, c))
        return
    end

    run = ns.Intermission.newRun(c.scheduleSeconds, c.leadSeconds)
    ensureTicker()
    if decision.reason == BossFilter.REASON.OVERRIDE then
        UI.Print(Locale.t("cmd.boss.overrideUsed"))
    end
    UI.Print(Locale.format("ui.armed", ns.Intermission.runRemaining(run), c.leadSeconds))
end

function UI.IntermissionOnEncounterEnd()
    run = nil
    UI.IntermissionStop()
    -- The MANUAL OVERRIDE lasts ONE encounter: it is consumed here, so the next
    -- encounter falls back to the configured target only.
    local db = _G.GideonRaidDB
    if type(db) == "table" and type(db.intermission) == "table" and db.intermission.overrideEncounter == true then
        db.intermission.overrideEncounter = false
        UI.Print(Locale.t("cmd.boss.overrideConsumed"))
    end
end

function UI.IntermissionSetEnabled(enabled)
    local db = _G.GideonRaidDB
    if type(db) ~= "table" or type(db.intermission) ~= "table" then
        UI.Print(Locale.t("ui.noSavedVariables"))
        return
    end
    db.intermission.enabled = enabled and true or false
    -- `/gr inter on` IS THE MANUAL OVERRIDE (raid-lead decision): besides enabling
    -- the module it arms the auto-opening for the NEXT encounter, WHATEVER the
    -- boss, and that arm is consumed at the end of the encounter. Disabling clears
    -- it, so it can never fire later on.
    db.intermission.overrideEncounter = enabled and true or false
    UI.Print(Locale.t(enabled and "ui.enabled" or "ui.disabledState"))
    if enabled then
        UI.Print(Locale.t("cmd.boss.overrideArmed"))
    end
end

function UI.IntermissionStatus()
    local c = config()
    local snap = ns.Intermission.snapshot(displayedState(), c.pingMode, resolveBindingKey)
    UI.Print(
        Locale.format(
            "ui.statusLine",
            Locale.t(c.enabled and "ui.wordEnabled" or "ui.wordDisabled"),
            snap.phase,
            tostring(snap.declaration)
        )
    )
    UI.Print(Locale.format("ui.timelineLine", c.visibilitySeconds, c.durationSeconds, c.scale))
    UI.Print(Locale.format("ui.pingPolicyLine", c.pingMode, snap.policyLine))
    UI.Print(Locale.format("ui.scheduleLine", #c.scheduleSeconds, c.leadSeconds))
    UI.Print(Locale.format("ui.soundLine", Locale.t(c.soundEnabled and "ui.wordEnabled" or "ui.wordDisabled")))
    -- WHICH BOSS may open the panel by itself: the allow-list of encounter ids (and
    -- names) of the auto-open filter, plus the state of the idlog.
    UI.Print(Locale.format("ui.bossLine", BossFilter.targetSummary(c), Locale.t(c.idlog and "ui.wordEnabled" or "ui.wordDisabled")))
end

--- `/gr inter ping`: which ping to use and which key to press, plus the binding
--- names tried (that is exactly what the in-game confirmation has to check).
function UI.IntermissionPrintPing()
    local c = config()
    local snap = ns.Intermission.snapshot(displayedState(), c.pingMode, resolveBindingKey)
    if snap.declaration == nil then
        UI.Print(Locale.t("ui.noDeclaration"))
        return
    end
    if snap.pingHint == nil then
        UI.Print(Locale.format("err.pingNotAllowed", tostring(snap.roleName), tostring(c.pingMode)))
        return
    end
    UI.Print(snap.pingHint.line)
    UI.Print(Locale.format("ui.pingCandidates", table.concat(snap.pingHint.bindNames, ", ")))
end

--- Prints the plan prepared out of game into the chat (same source as the panel).
function UI.PrintPlan()
    local me = UnitName("player")
    local c = config()
    local assignment, err = ns.Config.getAssignment()
    if not assignment then
        UI.Print(Locale.format("status.noAssignment", tostring(err)))
        return
    end
    local plan, planErr = ns.Intermission.buildPlan(assignment, me, c.pingMode, resolveBindingKey)
    if not plan then
        UI.Print(Locale.format("ui.unreadablePlan", tostring(planErr)))
        return
    end
    for _, line in ipairs(plan.lines) do
        UI.Print(line)
    end
end

--- Re-applies every LANGUAGE-DEPENDENT label (panel chrome + composition
--- buttons). Called at initialization and after a language change (/gr lang):
--- the strings come from Core, so the UI only copies them.
function UI.IntermissionApplyStaticText()
    local p = ensurePanel()
    -- The close cross is NOT part of a layout (it is chrome shared by the two
    -- panels): its label is refreshed here.
    p.closeCross:SetText(Locale.t("ui.closeCross"))
    -- The ping help window is built lazily: only refresh it when it exists.
    if pingPanel ~= nil then
        pingPanel.closeCross:SetText(Locale.t("ui.closeCross"))
        if pingPanel:IsShown() then
            UI.PingHelpRefresh()
        end
    end
    -- Everything else (title, buttons, disposition) is rebuilt from Core by a
    -- plain refresh: the labels live in Core/Layout.lua, in both languages.
    UI.IntermissionRefresh()
end

function UI.IntermissionInitialize()
    ensurePanel()
    UI.IntermissionApplyConfig()
    UI.IntermissionApplyStaticText()
end
